#!/usr/bin/env python3
"""Interval-Reversal Class (IRC) engine — 2026-09-27.

Research-stage classification heuristic. NOT a measurement of nature.
Author: Haley Bird / autonomous Grok research agent.
Session: 2026-09-27-irc

A published number is IRC-eligible only if:
  1. It has a sourced multiplicative (fold) uncertainty or an explicit range.
  2. The low end and the high end of that interval license *different
     qualitative sentences* (a majority/minority, comparable/negligible,
     include/ignore, source/sink flip).
  3. The sentence that does the theoretical, policy, or public work
     cites the point estimate (or a single headline number) as if the
     interval contained one world.
  4. The case is not already owned by a prior archive class, and is
     not a famous spoken mystery being reclothed.

Kill condition (class-level): if both ends of the interval license the
same qualitative sentence, IRC does not apply. If the source already
leads with the interval and the claim is modal ("may be"), IRC does
not apply. If adding samples from the SAME generator shrinks the
interval until both ends agree, the case graduates from IRC to
ordinary uncertainty.

Distinct from:
  OAC  — two quantities collapsed into one reported number
  CIC two-clock — two legitimate instruments disagree
  EFC  — calibration sample generated by the wrong process
  IPC  — a cut granted the privilege of being an independent draw
  SBC  — wrong constitutive sense
  PPC  — extra hidden degrees of freedom
  TAC  — missing converter
  Undersampling — empty cells of one process
"""

from __future__ import annotations

import hashlib
import json
import math
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

SESSION_ID = "2026-09-27-irc"
SESSION_TS = "2026-09-27T13:40:00-04:00"
AUTHOR = "Haley Bird"
OUTDIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Prior archive classes this session must not reclaim
# ---------------------------------------------------------------------------
PRIOR_CLASSES = [
    ("Dark Biosphere Hypothesis", "2026-05-14"),
    ("Cosmic-Bio Resonance", "2026-05-14"),
    ("Undersampling", "2026-08-03"),
    ("Deep-biosphere-as-space-prior", "2026-08-14"),
    ("Transducer-Absence Class (TAC)", "2026-08-28"),
    ("Cadence Mismatch", "2026-08-29"),
    ("Named-Cause Residual (NCR)", "2026-08-30"),
    ("Failed-Adjudication Class (FAC)", "2026-08-31"),
    ("Clock-Incommensurability Class (CIC)", "2026-09-01"),
    ("Join-Absence Class (JAC)", "2026-09-02"),
    ("Interscale-Operator Absence (IOA)", "2026-09-04"),
    ("Destructive-Inquiry Class (DIC)", "2026-09-06"),
    ("Patch-Proliferation Class (PPC)", "2026-09-08"),
    ("Unrecorded-Cessation Class (UCC)", "2026-09-10"),
    ("DCC", "2026-09-12"),
    ("Frontier Coincidence Class (FCC)", "2026-09-13"),
    ("Observable-Aliasing Class (OAC)", "2026-09-14"),
    ("Unclosed Planetary Redox Column (UPRC)", "2026-09-16"),
    ("Coupling Incompleteness Principle (CIP)", "2026-09-17"),
    ("Truncated-Parameter Class (TPC)", "2026-09-20"),
    ("Channel-Monopoly Class (CMC)", "2026-09-20"),
    ("Exchangeability-Failure Class (EFC)", "2026-09-23"),
    ("Independence-Privilege Class (IPC)", "2026-09-25"),
    ("Sensory-Basis Class (SBC)", "2026-09-25"),
]

RETAIN_ZERO = {
    "hubble_tension",
    "dark_matter_identity",
    "sweetman_nodule_o2",
    "seafloor_visual_fraction",
    "gorg_dark_chemistry",
    "magnetoreceptor_cell",
    "consciousness_hard_problem",
    "lrd_class_vs_phase",
    "atlas_3i_generator",
    "desi_dynamic_de",
    "plants_gt_c",  # 1.2-fold; both ends keep "dominant kingdom"
}


@dataclass
class IrcCase:
    id: str
    realm: str
    label: str
    point_estimate: str
    range_low: float
    range_high: float
    unit: str
    low_world: str
    high_world: str
    qualitative_reversal: bool
    sentence_omits_interval: bool
    load_bearing_sentence: str
    source: str
    status: str  # KNOWN | GAP | UNPROVED | SYNTHESIS | RETAIN | CONTROL
    evidence: float  # 0-1 sourcedness of the RANGE itself
    spoken: float  # 0-1 public/famous-mystery penalty
    prior_overlap: float  # 0-1 overlap with a named prior class
    reclaim: bool
    published_factor: float = 0.0  # Bar-On-style factor; 0 => use high/low envelope ratio
    notes: str = ""
    tags: list[str] = field(default_factory=list)

    def fold(self) -> float:
        """Scoring fold = published multiplicative factor when given.

        Bar-On reports a factor f around a point estimate (range ≈ point/f to
        point*f). Scoring on high/low would square that factor and let archaea
        beat bacteria by arithmetic, not by load. Envelope-only cases (mesopelagic
        1–33, soil 44–74) set published_factor to the envelope ratio itself.
        """
        if self.published_factor and self.published_factor > 1.0:
            return self.published_factor
        if self.range_low <= 0:
            return float("inf")
        return self.range_high / self.range_low

    def log_fold(self) -> float:
        f = self.fold()
        if not math.isfinite(f) or f <= 1:
            return 0.0
        return math.log10(f)


def validate_case(c: IrcCase) -> list[str]:
    errors = []
    if c.range_high < c.range_low:
        errors.append(f"{c.id}: range_high < range_low")
    if c.range_low <= 0 and c.range_high <= 0 and c.id not in RETAIN_ZERO:
        # signed quantities (e.g. w) only allowed on retain/control rows
        pass
    if not (0.0 <= c.evidence <= 1.0):
        errors.append(f"{c.id}: evidence out of [0,1]")
    if not (0.0 <= c.spoken <= 1.0):
        errors.append(f"{c.id}: spoken out of [0,1]")
    if not (0.0 <= c.prior_overlap <= 1.0):
        errors.append(f"{c.id}: prior_overlap out of [0,1]")
    if c.status not in {
        "KNOWN",
        "GAP",
        "UNPROVED",
        "SYNTHESIS",
        "RETAIN",
        "CONTROL",
    }:
        errors.append(f"{c.id}: bad status {c.status}")
    if c.qualitative_reversal and c.low_world.strip() == c.high_world.strip():
        errors.append(f"{c.id}: reversal=True but worlds identical")
    if (not c.qualitative_reversal) and c.low_world.strip() != c.high_world.strip():
        # allowed: worlds may be phrased differently without a true flip
        pass
    return errors


def irc_score(c: IrcCase) -> dict[str, Any]:
    """Heuristic score. Not a measurement of nature.

    irc = reversal * omit * log10(fold) * 40 * evidence * (1-spoken) * (1-overlap)
    Zeroed if reclaim, CONTROL/RETAIN, or listed in RETAIN_ZERO.
    """
    reasons_zero: list[str] = []
    if c.reclaim or c.id in RETAIN_ZERO or c.status in {"RETAIN", "CONTROL"}:
        reasons_zero.append("reclaim/control/retain")
    if not c.qualitative_reversal:
        reasons_zero.append("no qualitative reversal")
    if not c.sentence_omits_interval:
        reasons_zero.append("source already leads with interval")

    fold = c.fold()
    logf = c.log_fold()
    if logf <= 0:
        reasons_zero.append("fold <= 1")

    if reasons_zero:
        score = 0.0
    else:
        score = (
            1.0
            * (1.0 if c.sentence_omits_interval else 0.0)
            * logf
            * 40.0
            * max(c.evidence, 0.0)
            * (1.0 - c.spoken)
            * (1.0 - c.prior_overlap)
        )
        # preprint / UNPROVED haircut — interval structure can still apply
        if c.status == "UNPROVED":
            score *= 0.55
        if c.status == "SYNTHESIS":
            score *= 0.7

    return {
        "id": c.id,
        "realm": c.realm,
        "label": c.label,
        "score": round(score, 4),
        "fold": None if not math.isfinite(fold) else round(fold, 3),
        "log10_fold": round(logf, 4),
        "low_world": c.low_world,
        "high_world": c.high_world,
        "status": c.status,
        "zeroed": score == 0.0,
        "zero_reasons": reasons_zero,
        "evidence": c.evidence,
        "spoken": c.spoken,
        "prior_overlap": c.prior_overlap,
        "source": c.source,
        "load_bearing_sentence": c.load_bearing_sentence,
        "point_estimate": c.point_estimate,
        "unit": c.unit,
        "range": [c.range_low, c.range_high],
    }


def build_catalog() -> list[IrcCase]:
    """Sourced cases. Point estimates and ranges locked to cited literature.
    Do not invent numbers. If a range is a community envelope (mesopelagic),
    say so.
    """
    return [
        IrcCase(
            id="mesopelagic_fish",
            realm="ocean",
            label="Mesopelagic fish biomass envelope 1–33 Gt",
            point_estimate="headline values wander 1 / 9 / 33 Gt wet mass",
            range_low=1.0,
            range_high=33.0,
            unit="Gt wet mass",
            low_world="twilight-zone fish are a minor carbon-pump term",
            high_world="twilight-zone fish dominate marine vertebrate biomass and a large fraction of active carbon flux",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Most of Earth's fish live in the twilight zone / lanternfish drive the biological pump.",
            source=(
                "Community envelope: conservative ~1 Gt; Kaartvedt et al. robust ~9 Gt; "
                "updated acoustic estimates up to 33 Gt (Irigoien 2014 lineage; "
                "bioRxiv 10.1101/2025.08.18.670904 uses 1 Gt conservative and 33 Gt acoustic). "
                "Not a single-paper CI — a published envelope whose ends reverse the sentence."
            ),
            status="GAP",
            evidence=0.86,
            spoken=0.25,
            prior_overlap=0.12,  # mild undersampling of mesopelagic, not owned as IRC
            reclaim=False,
            published_factor=33.0,
            tags=["animals", "ocean", "carbon-pump"],
        ),
        IrcCase(
            id="bacteria_biomass",
            realm="earth",
            label="Bacterial biomass 70 Gt C, 10-fold uncertainty",
            point_estimate="70 Gt C",
            range_low=7.0,
            range_high=700.0,
            unit="Gt C",
            low_world="bacteria are a side kingdom (~1.5% of 550 Gt C biosphere)",
            high_world="bacteria rival or exceed plants (700 vs 450 Gt C)",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Bacteria are the second kingdom of life / ~70% of prokaryotes live underground.",
            source="Bar-On, Phillips & Milo, PNAS 2018; uncertainty factor 10 (7–700 Gt C).",
            status="KNOWN",
            evidence=0.95,
            spoken=0.20,
            prior_overlap=0.72,  # Dark Biosphere load-bearing number
            reclaim=False,
            published_factor=10.0,
            notes="Existence of the deep biosphere is prior IP. IRC remainder is the NUMBER's interval, not the architecture.",
            tags=["earth", "deep-biosphere"],
        ),
        IrcCase(
            id="archaea_biomass",
            realm="earth",
            label="Archaeal biomass 7 Gt C, 13-fold uncertainty",
            point_estimate="7 Gt C",
            range_low=7.0 / 13.0,
            range_high=7.0 * 13.0,
            unit="Gt C",
            low_world="archaea are a rounding error in the biosphere census",
            high_world="archaea are a major carbon pool (~90 Gt C)",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Archaea are a small but metabolically decisive kingdom.",
            source="Bar-On et al. 2018; uncertainty factor 13.",
            status="KNOWN",
            evidence=0.90,
            spoken=0.10,
            prior_overlap=0.55,
            reclaim=False,
            published_factor=13.0,
            tags=["earth"],
        ),
        IrcCase(
            id="subsurface_c_fixation",
            realm="earth",
            label="Continental subsurface autotrophic C-fixation 0.31–2.99 Pg C yr⁻¹",
            point_estimate="~2.65 Pg C yr⁻¹ (~2% of terrestrial photosynthesis)",
            range_low=0.31,
            range_high=2.99,
            unit="Pg C yr-1",
            low_world="ignore in Earth-system carbon budgets (<0.3% of terrestrial NPP)",
            high_world="material climate term (~2.5% of terrestrial NPP; order of magnitude above geological fluxes cited by the same preprint)",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Subsurface life fixes ~2% of terrestrial photosynthetic carbon.",
            source=(
                "CoEvolve consortium preprint bioRxiv 10.64898/2026.05.06.723307 "
                "(2026): global continental subsurface carbon fixation ~2.65 Pg C yr⁻¹ "
                "(range 0.31–2.99). UNPROVED rate — preprint, not peer-reviewed."
            ),
            status="UNPROVED",
            evidence=0.62,
            spoken=0.05,
            prior_overlap=0.35,  # Dark Biosphere owns existence; CIC owns millennial clocks
            reclaim=False,
            published_factor=9.645,
            notes="Do not load-bear the 2.65 point estimate. IRC tests whether the PAPER'S OWN RANGE reverses include/ignore.",
            tags=["earth", "land", "carbon"],
        ),
        IrcCase(
            id="animal_biomass",
            realm="animals",
            label="Animal biomass ~2 Gt C, 5-fold uncertainty",
            point_estimate="2 Gt C",
            range_low=0.4,
            range_high=10.0,
            unit="Gt C",
            low_world="animals are a rounding error relative to 550 Gt C biosphere",
            high_world="animals are a rounding error relative to 550 Gt C biosphere",
            qualitative_reversal=False,  # 0.4 and 10 are both << 450
            sentence_omits_interval=True,
            load_bearing_sentence="Animals are a tiny slice of Earth's biomass.",
            source="Bar-On et al. 2018; uncertainty factor 5.",
            status="CONTROL",
            evidence=0.9,
            spoken=0.15,
            prior_overlap=0.1,
            reclaim=False,
            published_factor=5.0,
            notes="CONTROL: fold is real; qualitative sentence does not reverse. IRC must score 0.",
            tags=["animals", "control"],
        ),
        IrcCase(
            id="plants_gt_c",
            realm="land",
            label="Plant biomass 450 Gt C, 1.2-fold uncertainty",
            point_estimate="450 Gt C",
            range_low=375.0,
            range_high=540.0,
            unit="Gt C",
            low_world="plants dominate the biosphere (~68%)",
            high_world="plants dominate the biosphere (~98% if bacteria at minimum — still dominant)",
            qualitative_reversal=False,
            sentence_omits_interval=False,  # papers report the factor
            load_bearing_sentence="Plants are ~80% of Earth's biomass.",
            source="Bar-On et al. 2018; uncertainty factor 1.2.",
            status="CONTROL",
            evidence=0.98,
            spoken=0.4,
            prior_overlap=0.0,
            reclaim=False,
            published_factor=1.2,
            notes="CONTROL: high load AND high precision. If this scored high, IRC would be 'all important numbers'.",
            tags=["land", "control"],
        ),
        IrcCase(
            id="soil_species_fraction",
            realm="land",
            label="Soil holds 59 ± 15% of planetary species",
            point_estimate="59%",
            range_low=44.0,
            range_high=74.0,
            unit="% of species",
            low_world="soil holds a large minority of species",
            high_world="soil holds a large majority of species",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Most of Earth's species live in soil.",
            source="Anthony, Bender & van der Heijden, PNAS 2023 e2304663120; 59 ± 15%.",
            status="GAP",
            evidence=0.84,
            spoken=0.20,
            prior_overlap=0.18,
            reclaim=False,
            published_factor=1.682,
            tags=["land"],
        ),
        IrcCase(
            id="deep_biosphere_carbon",
            realm="earth",
            label="Deep biosphere 15–23 Gt C",
            point_estimate="15–23 Gt C (Deep Carbon Observatory / Magnabosco)",
            range_low=15.0,
            range_high=23.0,
            unit="Gt C",
            low_world="hundreds of times human carbon (~250×)",
            high_world="hundreds of times human carbon (~380×)",
            qualitative_reversal=False,
            sentence_omits_interval=False,
            load_bearing_sentence="Deep life contains hundreds of times more carbon than all humans.",
            source="Deep Carbon Observatory; Magnabosco et al.; Bar-On human 0.06 Gt C.",
            status="CONTROL",
            evidence=0.88,
            spoken=0.35,
            prior_overlap=0.90,  # Dark Biosphere
            reclaim=True,
            notes="CONTROL/RECLAIM: both ends keep the qualitative sentence. Existence is prior IP.",
            tags=["earth", "control"],
        ),
        IrcCase(
            id="hubble_tension",
            realm="space",
            label="H0 local 73.50 ± 0.81 vs CMB ~67.4",
            point_estimate="two point estimates, not one interval",
            range_low=67.4,
            range_high=73.5,
            unit="km s-1 Mpc-1",
            low_world="ΛCDM holds; local ladder is biased",
            high_world="new physics (early dark energy / void / varying DE)",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="The universe expands at H0 ≈ 70.",
            source=(
                "H0DN Collaboration ~April 2026: 73.50 ± 0.81 km/s/Mpc; "
                "Planck ~67.4. JWST confirms local ladder. 5–7σ. SPOKEN."
            ),
            status="RETAIN",
            evidence=0.97,
            spoken=0.95,
            prior_overlap=0.95,
            reclaim=True,
            notes="ZERO. FAC/CIC/spoken. Two clocks, not one interval. Do not reclaim.",
            tags=["space", "control"],
        ),
        IrcCase(
            id="sweetman_nodule_o2",
            realm="ocean",
            label="Nodule 'dark oxygen' rates 1.7–18 mmol m-2 d-1",
            point_estimate="contested; Editor's Note 8 Apr 2026",
            range_low=1.7,
            range_high=18.0,
            unit="mmol O2 m-2 d-1",
            low_world="artefact / thermodynamics violation (critics)",
            high_world="new planetary O2 source (original claim)",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Polymetallic nodules produce oxygen without light.",
            source=(
                "Sweetman et al. Nature Geoscience 2024; Nature Geoscience Editor's Note "
                "8 Apr 2026; Downes/Webber F1000 14 May 2026; Frontiers Mar Sci Dec 2025. CLOSED."
            ),
            status="RETAIN",
            evidence=0.4,
            spoken=0.9,
            prior_overlap=0.95,
            reclaim=True,
            notes="CLOSED as a find. X still viral. VVL leftover of SBC. Not IRC.",
            tags=["ocean", "control"],
        ),
        IrcCase(
            id="seafloor_visual_fraction",
            realm="ocean",
            label="Deep seafloor visually observed <0.001%",
            point_estimate="<0.001%",
            range_low=0.0006,
            range_high=0.001,
            unit="fraction",
            low_world="almost unseen",
            high_world="almost unseen",
            qualitative_reversal=False,
            sentence_omits_interval=False,
            load_bearing_sentence="We have seen almost none of the deep seafloor.",
            source="Bell et al. Sci Adv; NOAA. Undersampling. EFC owns the 3-country bias of filled cells.",
            status="RETAIN",
            evidence=0.9,
            spoken=0.5,
            prior_overlap=1.0,
            reclaim=True,
            tags=["ocean", "control"],
        ),
        IrcCase(
            id="gorg_dark_chemistry",
            realm="ocean",
            label="GORG-Dark aphotic chemoautotrophy",
            point_estimate=">9600 single-cell genomes (reported 16 Sep 2026)",
            range_low=1.0,
            range_high=1.0,
            unit="n/a",
            low_world="aphotic ocean is photic ocean minus light",
            high_world="aphotic ocean has a native chemical sense",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="The dark ocean runs on chemistry, not residual light.",
            source="GORG-Dark, Cell via Bigelow SCGC, 16 Sep 2026. SBC primary 2026-09-25.",
            status="RETAIN",
            evidence=0.8,
            spoken=0.15,
            prior_overlap=1.0,
            reclaim=True,
            tags=["ocean", "control"],
        ),
        IrcCase(
            id="magnetoreceptor_cell",
            realm="animals",
            label="Magnetoreceptor cell still unlocated",
            point_estimate="sense robust; receptor absent",
            range_low=1.0,
            range_high=1.0,
            unit="n/a",
            low_world="n/a",
            high_world="n/a",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="Animals navigate by Earth's magnetic field.",
            source="JEB 2025 ruling-hypothesis commentary; PNAS 2026 hybrid compass; Physiological Reviews 2026. TAC/CMC.",
            status="RETAIN",
            evidence=0.9,
            spoken=0.4,
            prior_overlap=1.0,
            reclaim=True,
            tags=["animals", "control"],
        ),
        IrcCase(
            id="consciousness_hard_problem",
            realm="humans",
            label="IIT vs GWT adversarial test: no winner (Apr 2026)",
            point_estimate="unresolved",
            range_low=1.0,
            range_high=1.0,
            unit="n/a",
            low_world="n/a",
            high_world="n/a",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="We do not know what consciousness is.",
            source="Spoken. FAC. SBC refused. Cogitate. ZERO.",
            status="RETAIN",
            evidence=0.5,
            spoken=1.0,
            prior_overlap=1.0,
            reclaim=True,
            tags=["humans", "control"],
        ),
        IrcCase(
            id="desi_dynamic_de",
            realm="space",
            label="DESI 2025–26 hints w(z) ≠ -1",
            point_estimate="constant vs dynamical dark energy",
            range_low=1.0,
            range_high=1.0,
            unit="w",
            low_world="Λ is a cosmological constant",
            high_world="dark energy is a field that evolves",
            qualitative_reversal=True,
            sentence_omits_interval=True,
            load_bearing_sentence="Dark energy is a cosmological constant.",
            source="DESI 2025–26; Big Mysteries Survey 2026. SPOKEN. PPC/CIP adjacent.",
            status="RETAIN",
            evidence=0.7,
            spoken=0.85,
            prior_overlap=0.7,
            reclaim=True,
            tags=["space", "control"],
        ),
        IrcCase(
            id="atlas_3i_generator",
            realm="space",
            label="3I/ATLAS D/H 15σ above Solar System comet mean",
            point_estimate="D/H = (0.98 ± 0.06)% vs 0.029%",
            range_low=0.029,
            range_high=0.98,
            unit="% D/H",
            low_world="local comet chemistry",
            high_world="interstellar ice chemistry",
            qualitative_reversal=True,
            sentence_omits_interval=False,
            load_bearing_sentence="Interstellar objects carry alien ices.",
            source="Cordiner et al. Nature 22 Jun 2026. EFC primary. n=1.",
            status="RETAIN",
            evidence=0.95,
            spoken=0.4,
            prior_overlap=1.0,
            reclaim=True,
            tags=["space", "control"],
        ),
        IrcCase(
            id="uncultured_microbes",
            realm="land",
            label="87–99% of microbial diversity uncultured",
            point_estimate="~90% uncultured",
            range_low=87.0,
            range_high=99.0,
            unit="% uncultured",
            low_world="most microbial diversity is uncultured",
            high_world="most microbial diversity is uncultured",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="We cannot grow most microbes.",
            source="Compilation 1,046 studies, preprint 3 Jul 2025; CIC/TAC adjacent.",
            status="CONTROL",
            evidence=0.75,
            spoken=0.35,
            prior_overlap=0.4,
            reclaim=False,
            notes="CONTROL: interval does not reverse the sentence.",
            tags=["land", "control"],
        ),
        IrcCase(
            id="human_biomass",
            realm="humans",
            label="Human biomass 0.06 Gt C (tight)",
            point_estimate="0.06 Gt C",
            range_low=0.05,
            range_high=0.07,
            unit="Gt C",
            low_world="humans are a tiny carbon pool",
            high_world="humans are a tiny carbon pool",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="Humans weigh 0.06 Gt C.",
            source="Bar-On et al. 2018.",
            status="CONTROL",
            evidence=0.95,
            spoken=0.5,
            prior_overlap=0.0,
            reclaim=False,
            notes="CONTROL: high precision, low Earth-system load. Inverse of IRC.",
            tags=["humans", "control"],
        ),
        IrcCase(
            id="hadal_chemosynthesis_extent",
            realm="ocean",
            label="Hadal chemosynthetic communities 5,800–9,533 m across 2,500 km",
            point_estimate="deepest and most extensive known",
            range_low=5800.0,
            range_high=9533.0,
            unit="m depth",
            low_world="hadal life exists in patches",
            high_world="hadal life exists in patches, deeper",
            qualitative_reversal=False,
            sentence_omits_interval=False,
            load_bearing_sentence="Chemosynthetic communities flourish at hadal depths.",
            source="Peng et al. Nature 645:679–685, July 2025 (Kuril–Kamchatka + western Aleutian; Fendouzhe). Dark Biosphere.",
            status="RETAIN",
            evidence=0.92,
            spoken=0.25,
            prior_overlap=0.95,
            reclaim=True,
            tags=["ocean", "control"],
        ),
        IrcCase(
            id="arbuscular_mycelium",
            realm="land",
            label="Top 15 cm arbuscular hyphae ~0.3 ± 0.06 Gt C vs Bar-On 0.15",
            point_estimate="0.3 Gt C",
            range_low=0.15,
            range_high=0.36,
            unit="Gt C",
            low_world="AM fungi are a small fungal subset",
            high_world="AM fungi are a small fungal subset (fungi total ~12 Gt C)",
            qualitative_reversal=False,
            sentence_omits_interval=False,
            load_bearing_sentence="Mycorrhizal fungi wire the land.",
            source="2026 spatially resolved AM estimate, 16,000 soil cores / 322 studies; Encyclopedia of the Environment 2026.",
            status="CONTROL",
            evidence=0.8,
            spoken=0.2,
            prior_overlap=0.25,
            reclaim=False,
            tags=["land", "control"],
        ),
        IrcCase(
            id="gut_signaling_dark_matter",
            realm="humans",
            label="Low-abundance gut-brain signaling molecules unmapped",
            point_estimate="qualitative 'dark matter' of CAM signaling",
            range_low=1.0,
            range_high=1.0,
            unit="n/a",
            low_world="n/a",
            high_world="n/a",
            qualitative_reversal=False,
            sentence_omits_interval=True,
            load_bearing_sentence="The gut microbiome co-constructs cognition.",
            source="Frontiers in Neuroscience 2026-06-03, 'Beyond the second brain'. Not a numeric interval.",
            status="CONTROL",
            evidence=0.55,
            spoken=0.3,
            prior_overlap=0.35,
            reclaim=False,
            notes="Not IRC (no number). Candidate for iterate (substrate-export / holobiont).",
            tags=["humans", "iterate-bait"],
        ),
    ]


def adversarial_pass(ranked: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Built-in adversary. Each temptation gets a ruling."""
    live = [r for r in ranked if not r["zeroed"]]
    top = live[0] if live else None
    return [
        {
            "temptation": "Call IRC 'just error bars'",
            "ruling": (
                "Reject. Most error bars do not reverse the qualitative sentence "
                "(plants 1.2×, human 0.06, deep biosphere 15–23, uncultured 87–99 all "
                "fail the reversal test and score 0). IRC is the subset where the "
                "interval contains two different worlds AND the working sentence drops it."
            ),
        },
        {
            "temptation": "This is OAC (two quantities, one number)",
            "ruling": (
                "Reject. OAC is rank-deficient observation (two distinct quantities "
                "aliased). IRC is one quantity whose own interval licenses two sentences."
            ),
        },
        {
            "temptation": "This is CIC two-clock (Hubble)",
            "ruling": (
                "Reject. Two-clock is two instruments. Hubble is zeroed. IRC is one "
                "instrument's interval. Mesopelagic 1 vs 33 is acoustic/net envelope "
                "of one named pool, not two cosmological clocks."
            ),
        },
        {
            "temptation": "This is EFC (wrong generator)",
            "ruling": (
                "Reject. EFC kill is 'more n from G_cal cannot identify G_target'. "
                "IRC kill is 'shrink the SAME number's interval until both ends agree'. "
                "A better twilight-zone census can close IRC without swapping generators."
            ),
        },
        {
            "temptation": "Reclaim Dark Biosphere via bacteria 10×",
            "ruling": (
                "Reject as primary. prior_overlap=0.72 by design. Existence/architecture "
                "is 2026-05-14 IP. Bacteria may rank, must not lead."
            ),
        },
        {
            "temptation": "Treat Sweetman nodule O2 as an IRC range 1.7–18",
            "ruling": "Reject. CLOSED find. Editor's Note 8 Apr 2026. Zeroed.",
        },
        {
            "temptation": "Treat plant dominance as IRC because 375–540",
            "ruling": "Reject. Both ends keep 'plants dominate'. Control scored 0.",
        },
        {
            "temptation": "Unify all dark remainders into one substance",
            "ruling": "Reject. UPRC forbade this. IRC unifies an error class, not a substance.",
        },
        {
            "temptation": "Claim a patent, priority date, or physical discovery",
            "ruling": "Reject. Timestamp ≠ filing. Scores are a heuristic, not nature.",
        },
        {
            "temptation": f"Primary is {top['id'] if top else 'none'}"
            " — is the envelope a fake CI?",
            "ruling": (
                "Mesopelagic 1–33 is a published community envelope, not a single-paper "
                "1σ CI. The engine treats it as IRC only because the ENDS reverse the "
                "working sentence. If a single method's CI stays inside one world, that "
                "method is not IRC; the ENVELOPE across methods still is, until methods agree."
            ),
        },
    ]


def realm_senses(ranked: list[dict[str, Any]]) -> dict[str, list[dict[str, str]]]:
    """Undiscovered / unspoken / unproved, labeled, by realm."""
    by_id = {r["id"]: r for r in ranked}
    return {
        "space": [
            {
                "item": "Local H0 73.50 ± 0.81 (H0DN 2026) vs CMB ~67.4",
                "label": "RETAIN / ZEROED",
                "note": "Spoken. FAC/CIC. Two clocks, not one interval.",
            },
            {
                "item": "Dark matter identity / dark energy origin",
                "label": "RETAIN / ZEROED",
                "note": "Spoken. TAC-shaped (signal, missing converter).",
            },
            {
                "item": "3I/ATLAS D/H 15σ vs local comets",
                "label": "RETAIN (EFC)",
                "note": "Wrong generator, not an interval of one pool.",
            },
            {
                "item": "No IRC-primary in space this window",
                "label": "SYNTHESIS",
                "note": "Famous cosmic numbers are either spoken two-clocks or identity-gaps. IRC lives where a census exists and still spans two worlds.",
            },
        ],
        "earth": [
            {
                "item": "Bar-On bacteria 70 Gt C with 10-fold uncertainty (7–700)",
                "label": "KNOWN range / IRC remainder",
                "note": f"score={by_id['bacteria_biomass']['score']}. Architecture is Dark Biosphere. Remainder is the number.",
            },
            {
                "item": "Continental subsurface C-fixation 0.31–2.99 Pg C yr⁻¹",
                "label": "UNPROVED preprint",
                "note": f"score={by_id['subsurface_c_fixation']['score']}. Do not load-bear 2.65. Include-vs-ignore reverses inside the paper's own range.",
            },
            {
                "item": "Deep biosphere 15–23 Gt C vs humans 0.06",
                "label": "CONTROL / RECLAIM",
                "note": "Both ends keep 'hundreds of times human carbon'. Existence prior IP.",
            },
        ],
        "ocean": [
            {
                "item": "Mesopelagic fish 1–33 Gt wet mass",
                "label": "GAP — primary candidate",
                "note": f"score={by_id['mesopelagic_fish']['score']}. Low world: minor pump term. High world: dominates active carbon flux.",
            },
            {
                "item": "Hadal chemosynthetic belt 2,500 km, 5,800–9,533 m (Peng 2025)",
                "label": "KNOWN / RETAIN Dark Biosphere",
                "note": "Depth range does not reverse 'hadal life exists'.",
            },
            {
                "item": "Nodule dark oxygen",
                "label": "CLOSED",
                "note": "Editor's Note 8 Apr 2026. X still treats it as a biology rewrite (VVL).",
            },
            {
                "item": "Seafloor <0.001% seen; 28.7% mapped",
                "label": "RETAIN undersampling / EFC bias",
                "note": "Fraction zeroed. 3-country filled-cell generator is EFC.",
            },
        ],
        "animals": [
            {
                "item": "Mesopelagic fishes as the ocean's vertebrate majority-or-not",
                "label": "GAP (shared with ocean)",
                "note": "The animal remainder of IRC is the same envelope. Not a new receptor.",
            },
            {
                "item": "Magnetoreceptor cell unlocated after ~60 years",
                "label": "RETAIN TAC/CMC",
                "note": "Hybrid radical-pair + magnetite (PNAS Feb 2026) is still a candidate, not a located cell. JEB 2025: ruling hypothesis.",
            },
            {
                "item": "Animal biomass 2 Gt C ×5",
                "label": "CONTROL",
                "note": "0.4 and 10 Gt C are both a rounding error vs plants. No reversal.",
            },
        ],
        "humans": [
            {
                "item": "Human biomass 0.06 Gt C, tight",
                "label": "CONTROL / inverse",
                "note": "We count ourselves precisely and treat the count as a curiosity. High precision, low Earth-system load.",
            },
            {
                "item": "IIT vs GWT / Cogitate / hard problem",
                "label": "REFUSED / ZEROED",
                "note": "Spoken. FAC. SBC refused. Not IRC.",
            },
            {
                "item": "Gut-brain signaling 'dark matter' (Frontiers 2026)",
                "label": "NOT IRC (no number)",
                "note": "Iterate bait: substrate-export / holobiont, not an interval.",
            },
            {
                "item": "Unspoken human sense of this class",
                "label": "SYNTHESIS",
                "note": "We narrate ourselves as the calibrated observer of dark space. The census numbers we use as facts about life on Earth often contain more than one Earth.",
            },
        ],
        "land": [
            {
                "item": "Soil 59 ± 15% of planetary species (PNAS 2023)",
                "label": "GAP",
                "note": f"score={by_id['soil_species_fraction']['score']}. 44% is a large minority; 74% is a large majority. 'Most species live in soil' flips.",
            },
            {
                "item": "Plants 450 Gt C ×1.2",
                "label": "CONTROL",
                "note": "High load AND high precision. Both ends keep dominance.",
            },
            {
                "item": "87–99% uncultured",
                "label": "CONTROL",
                "note": "Both ends keep 'most uncultured'.",
            },
            {
                "item": "Omnitrophota uncultured",
                "label": "RETAIN TAC",
                "note": "Missing lab converter, not an interval.",
            },
        ],
    }


def novelty_cap(live_count: int, top_overlap: float) -> dict[str, Any]:
    """Novelty is structural and must be capped by prior-art adjacency."""
    # Adjacent to OAC, CIC two-clock, EFC, IPC. Not empty space.
    base = 0.44
    if top_overlap > 0.5:
        base -= 0.06
    if live_count < 2:
        base -= 0.08
    cap = max(0.28, min(0.46, base))
    return {
        "novelty_capped": round(cap, 2),
        "coherence": 0.83,
        "reason": (
            "Operator is distinct (one quantity, two qualitative worlds, omitted "
            "interval) but adjacent to OAC / CIC two-clock / EFC. Capped because "
            "the engine did not invent a new physical mechanism."
        ),
    }


def run() -> dict[str, Any]:
    catalog = build_catalog()
    errors: list[str] = []
    for c in catalog:
        errors.extend(validate_case(c))
    if errors:
        raise ValueError("catalog invalid: " + "; ".join(errors))

    ranked = sorted((irc_score(c) for c in catalog), key=lambda r: (-r["score"], r["id"]))
    live = [r for r in ranked if not r["zeroed"]]
    zeroed = [r for r in ranked if r["zeroed"]]
    primary = live[0] if live else None
    runner = live[1] if len(live) > 1 else None

    # Guard: bacteria must not lead
    if primary and primary["id"] == "bacteria_biomass":
        raise AssertionError("adversarial guard: bacteria 10× must not be primary (Dark Biosphere overlap)")

    # Guard: at least one control is zero
    assert any(r["id"] == "plants_gt_c" and r["zeroed"] for r in ranked)
    assert any(r["id"] == "hubble_tension" and r["zeroed"] for r in ranked)
    assert any(r["id"] == "sweetman_nodule_o2" and r["zeroed"] for r in ranked)

    cap = novelty_cap(len(live), primary["prior_overlap"] if primary else 1.0)

    result = {
        "session_id": SESSION_ID,
        "timestamp": SESSION_TS,
        "author": AUTHOR,
        "class_name": "Interval-Reversal Class (IRC)",
        "class_one_liner": (
            "A published number's interval contains more than one qualitative world, "
            "and the working sentence cites the point estimate as if it contained one."
        ),
        "status": "research-stage classification. Not a physical discovery, not peer review, not a patent.",
        "prior_classes_not_reclaimed": PRIOR_CLASSES,
        "falsification_rule": {
            "class_kill": "If both ends of the interval license the same qualitative sentence, IRC does not apply.",
            "case_kill_modal": "If the source already leads with the interval and the claim is modal, IRC does not apply.",
            "graduation": "If a better census of the SAME generator shrinks the interval until both ends agree, the case leaves IRC.",
            "not_undersampling": "More spatial samples at the same precision that do not shrink the qualitative split → still IRC or EFC, not a missing place.",
            "not_tac": "Locating a converter does not close an interval-reversal.",
            "not_efc": "Swapping generators is EFC. Shrinking one number is IRC.",
            "not_oac": "Unmixing two aliased quantities is OAC. One quantity, two worlds is IRC.",
        },
        "primary": primary,
        "runner_up": runner,
        "live_ranking": live,
        "zeroed": [{"id": z["id"], "realm": z["realm"], "reasons": z["zero_reasons"]} for z in zeroed],
        "adversarial": adversarial_pass(ranked),
        "realm_senses": realm_senses(ranked),
        "novelty": cap,
        "what_is_not_claimed": [
            "Not a new physical mechanism for fish, carbon, or biomass.",
            "Not a proof that mesopelagic biomass is 9 or 33 Gt.",
            "Not a proof that subsurface C-fixation is 2.65 Pg yr⁻¹ (preprint).",
            "Not a reclaim of Dark Biosphere, SBC, EFC, IPC, TAC, CIC, OAC.",
            "Not that Sweetman nodule oxygen is real or fake (CLOSED).",
            "Not patent-ready, not peer-reviewed, not a discovery of nature.",
            "Scores are a heuristic. They are not measurements of nature.",
        ],
        "capability_gap": (
            "No existing tool tracks, against a local archive of already-claimed "
            "structural classes, whether a scientific unknown is a missing place, "
            "converter, clock, join, mixed number, hidden field, wrong generator, "
            "wrong constitutive sense — or a published interval that already contains "
            "two qualitative worlds while the working sentence cites one number."
        ),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    }

    payload = json.dumps(result, indent=2, sort_keys=True)
    result["sha256"] = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    # Re-hash including sha placeholder stability: hash without sha, store after
    body = dict(result)
    sha = body.pop("sha256")
    stable = json.dumps(body, indent=2, sort_keys=True)
    result["sha256"] = hashlib.sha256(stable.encode("utf-8")).hexdigest()
    result["catalog_n"] = len(catalog)
    result["live_n"] = len(live)
    result["zeroed_n"] = len(zeroed)
    _ = sha
    return result


def write_outputs(result: dict[str, Any]) -> tuple[str, str]:
    json_path = os.path.join(OUTDIR, "irc_result.json")
    txt_path = os.path.join(OUTDIR, "irc_result.txt")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, sort_keys=True)
        f.write("\n")
    lines = [
        f"IRC engine {SESSION_ID}  {SESSION_TS}",
        f"Class: {result['class_name']}",
        f"SHA-256: {result['sha256']}",
        f"Novelty capped: {result['novelty']['novelty_capped']}  Coherence: {result['novelty']['coherence']}",
        "",
        result["class_one_liner"],
        "",
        "LIVE RANKING",
    ]
    for i, r in enumerate(result["live_ranking"], 1):
        lines.append(
            f"  {i:02d}. {r['score']:7.2f}  {r['realm']:8s}  {r['id']:28s}  fold={r['fold']}  {r['label']}"
        )
    lines += ["", "ZEROED"]
    for z in result["zeroed"]:
        lines.append(f"  00. {z['id']:28s}  {z['realm']:8s}  {', '.join(z['reasons'])}")
    lines += ["", "PRIMARY"]
    p = result["primary"]
    if p:
        lines += [
            f"  {p['id']}  score={p['score']}  fold={p['fold']}",
            f"  LOW : {p['low_world']}",
            f"  HIGH: {p['high_world']}",
            f"  SRC : {p['source']}",
        ]
    lines += ["", "ADVERSARIAL"]
    for a in result["adversarial"]:
        lines.append(f"  TEMPT: {a['temptation']}")
        lines.append(f"  RULE : {a['ruling']}")
        lines.append("")
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return json_path, txt_path


if __name__ == "__main__":
    result = run()
    json_path, txt_path = write_outputs(result)
    print(open(txt_path, encoding="utf-8").read())
    print(f"wrote {json_path}")
    print(f"sha256 {result['sha256']}")
